/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parschedule;

import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void emptyTest() {

    }
}
